version: 2.1
jobs:
  tests:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: npm i
      - run: npm t
      - run: npm run lint

workflows:
  version: 2.1
  ci:
    jobs:
      - tests
